function sources = add_deformation_field(sources, bf, map, verbose, deformation_field_needed)
    % (C) Copyright 2021 spm_2_bids developers

    deformation_field = 'TODO: add deformation field';

    % TODO? grab all the anat suffixes from BIDS schema?
    covered_suffixes = {'T1w', ...
                        'T2w', ...
                        'PDw', ...
                        'T2starw', ...
                        'inplaneT1', ...
                        'inplaneT2', ...
                        'PD', ...
                        'PDT2', ...
                        'T2star', ...
                        'FLASH', ...
                        'T1map', ...
                        'T2map', ...
                        'T2starmap', ...
                        'R1map', ...
                        'R2map', ...
                        'R2starmap', ...
                        'PDmap', ...
                        'UNIT1'};

    if deformation_field_needed

        % for anatomical data we assume that
        % the deformation field comes from the anatomical file itself
        if (~isempty(bf.modality) && ismember(bf.modality, {'anat'})) || ...
           (~isempty(bf.suffix) && ismember(bf.suffix, covered_suffixes))

            bf.prefix = 'y_';
            bf = bf.update;
            new_filename = spm_2_bids(bf.filename, map, verbose);
            deformation_field = fullfile(bf.bids_path, new_filename);

            % otherwise we can't guess it just from the file name
        else

        end

        sources{2, 1} = deformation_field;

    end
end
